/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterTags: typeof import('./src/components/router-tags/index.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/search-form/index.vue')['default']
    ThemeSwitch: typeof import('./src/components/theme-switch/index.vue')['default']
  }
}
